#!/bin/bash
rm -f *.a *.o *.cmi *.cmx *.dll *.so *.dylib cpdflibtest cpdflibtest-withshared
rm -f testoutputs/*
rm -f foo
rm -f merged.pdf merge
rm -f squeezed.pdf squeeze
rm -f *.aux *.idx *.log *.out *.toc
