#!/bin/bash
rm -f *.a *.o *.cmi *.cmx *.dll *.so *.dylib cpdflibtest cpdflibtest-withshared *.rtYk1s
rm -f testoutputs/*
rm -f foo foo2
rm -f examples/merged.pdf examples/merge examples/merge.o
rm -f examples/squeezed.pdf examples/squeeze examples/squeeze.o
rm -f examples/rde.pdf examples/rde examples/rde.o
rm -f examples/libcpdf.dll
rm -f *.aux *.idx *.log *.out *.toc
