#!/bin/bash
rm -f *.a *.o *.cmi *.cmx *.dll *.so *.dylib cpdflibtest cpdflibtest-withshared
rm -f testoutputs/*
rm -f foo
rm -f examples/merged.pdf examples/merge examples/merge.o
rm -f examples/squeezed.pdf examples/squeeze examples/squeeze.o
rm -f *.aux *.idx *.log *.out *.toc
