/* test.c */
#include <stdio.h>
#include "cpdflibwrapper.h"
int main (int argc, char ** argv)
{
  caml_startup(argv);
  int pdf = fromFile("logo.pdf");
  //toFile(pdf, "d1.pdf", 0, 0);
  //aboutToUpdateDeep(pdf);
  //toFile(pdf, "d2.pdf", 0, 0);
  decryptPdf(pdf, "");
  //toFile(pdf, "d3.pdf", 0, 0);
  //abortUpdate(pdf);
  //toFile(pdf, "d4.pdf", 0, 0);
  //decryptPdfOwner(pdf, "fred");
  toFile(pdf, "out.pdf", 0, 0);
  //int final = fromFile("bit3bit12.pdf");
 // printf("final is %i\n", final);
  //decryptPdf(final, "user");
  //toFile(final, "decrypted.pdf", 0, 0);
  //int original = fromFile("bit3bit12.pdf");
  //printf("original is %i\n", original);
  //int file = fromFile("hello.pdf");
  //int r = range(1, 1);
  //int pdf = selectPages(final, r);
  //printf("selectedpages is %i\n", pdf);
  //int pdf = selectPages(file, r);
  //toFile(pdf, "selected-pages.pdf", 0, 0);
  //int out = recryptPdf(original, pdf, "user");
  //printf("recrypted is %i\n", out);
  //toFileRecrypting(original, pdf, "user", "recrypted.pdf");
  /*set_progress_callback (&progress_called);
  printf("10 cm is %f points\n", ptOfCm(10.0));
  printf("10 mm is %f points\n", ptOfMm(10.0));
  printf("10 in is %f points\n", ptOfIn(10.0));
  printf("10 pt is %f cm\n", cmOfPt(10.0));
  printf("10 pt is %f mm\n", mmOfPt(10.0));
  printf("10 pt is %f in\n", inOfPt(10.0));
  int r = range(2, 9);
  int r2 = odd(r);
  int r3 = even(r);
  int r4 = range_union(r2, r3);
  int r5 = difference(r2, r3);
  int r6 = removeDuplicates(r2);
  int hello = fromFile("hello.pdf");
  printf("File hello.pdf loaded as file number %i\n", hello);
  toFile(hello, "hello-out.pdf", 0, 0);
  int hello2 = fromFileLazy("hello.pdf");
  printf("File hello.pdf loaded as file number %i\n", hello2);
  toFile(hello2, "hello-out-lazy.pdf", 0, 0);
  int hello3 = fromFile("hello.pdf");
  printf("File hello.pdf loaded as file number %i\n", hello3);
  int hello_dec = fromFileDecrypt("", "hello.pdf");
  toFile(hello3, "hello-out-decrypt.pdf", 0, 0);
  int blankdoc = blankDocument(200.0, 400.0, 5);
  printf("blankdoc is PDF %i\n", blankdoc);
  int blankdoc_r = all(blankdoc);
  printf("blankdoc-r is Range %i\n", blankdoc_r);
  char * str = stringOfPagespec(blankdoc, blankdoc_r);
  printf("this range is $%s$\n", str);
  int r7 = parsePagespec(blankdoc, str);
  int x2;
  int rl = rangeLength(r7);
  printf("rangeLength(r7) is %i\n", rl);
  for(x2 = 0; x2 < rl; x2++)
  {
    printf("pos %i, value %i\n", x2, rangeGet(r7, x2));
  }
  printf("Writing to blankdoc...");
  toFile(blankdoc, "blankdoc.pdf", 0, 0);
  int blankdoc2 = blankDocumentPaper(a4landscape, 4);
  toFile(blankdoc2, "blankdoc-paper.pdf", 0, 0);
  printf("The file has %i pages\n", pages(blankdoc2));
  int allpages = all(blankdoc2);
  printf("All pages in file:\n");
  int x;
  printf("isEncrypted: %i\n", isEncrypted(blankdoc2));
  int permissions[2];
  permissions[0] = noPrint;
  permissions[1] = noCopy;
  toFileEncrypted(blankdoc2, pdf40bit, permissions, 2, "owner", "user", 1, "blank-enc.pdf");
  int pdfs[2];
  pdfs[0] = blankdoc2;
  pdfs[1] = hello3;
  int merged = mergeSimple(pdfs, 2);
  toFile(merged, "merged.pdf", 1, 1);
  int merged2 = merge(pdfs, 2, 0, 0);
  toFile(merged2, "merged2.pdf", 1, 1);
  int selected = selectPages(hello3, r);
  toFile(selected, "selectPages.pdf", 1, 1);
  int numsplits;
  int* splits = splitOnBookmarks(selected, 0, &numsplits);
  printf("numsplits is %i\n", numsplits);
  compress(selected);
  decompress(selected);
  toFile(selected, "decompressed.pdf", 1, 1);
  int allpages2 = all(selected);
  printf("scalePages\n");
  scalePages(selected, allpages2, 2.5, 1.0);
  printf("scaleToFit\n");
  scaleToFit(selected, allpages2, 200.0, 200.0);
  printf("scaleToFitPaper\n");
  scaleToFitPaper(selected, allpages2, a4portrait);
  rotate(selected, allpages2, 90);
  printf("rotate\n");
  rotateBy(selected, allpages2, 90);
  printf("rotateby\n");
  rotateContents(selected, allpages2, 35.0);
  printf("rotateContents\n");
  hFlip(selected, allpages2);
  printf("hFlip\n");
  vFlip(selected, allpages2);
  printf("vFlip\n");
  crop(selected, allpages2, 0.0, 0.0, 200.0, 200.0);
  printf("crop\n");
  removeCrop(selected, allpages2);
  printf("removeCrop\n");
  setMediabox(selected, allpages2, 0.0, 0.0, 250.0, 250.0);
  printf("end\n");
  struct position p;
  p.anchor = 0;
  p.coord1 = 100.0;
  p.coord2 = 100.0;
  scaleContents(selected, allpages2, p, 2.0);
  draft(selected, 1);
  blackText(selected, allpages2);
  blackLines(selected, allpages2);
  blackFills(selected, allpages2);
  thinLines(selected, allpages2, 2.0);
  copyId(selected, merged);
  attachFile("hello.pdf", selected);
  toFile(selected, "scaled.pdf", 1, 1);
  //Chapter 11 - Document Information and Metadata
  setVersion(selected, 2);
  setTitle(selected, "Title");
  setAuthor(selected, "Author");
  setSubject(selected, "Subject");
  setKeywords(selected, "Keywords");
  setCreator(selected, "Creator");
  setProducer(selected, "Producer");
  setCreationDate(selected, "CreationDate");
  setModificationDate(selected, "ModificationDate");
  printf("PDF Version: %i\n", getVersion(selected));
  printf("Title: %s\n", getTitle(selected));
  printf("Author: %s\n", getAuthor(selected));
  printf("Subject: %s\n", getSubject(selected));
  printf("Keywords: %s\n", getKeywords(selected));
  printf("Creator: %s\n", getCreator(selected));
  printf("Producer: %s\n", getProducer(selected));
  printf("CreationDate: %s\n", getCreationDate(selected));
  printf("ModificationDate: %s\n", getModificationDate(selected));
  markTrapped(selected);
  markUntrapped(selected);
  setPageLayout(selected, 0);
  setPageMode(selected, 0);
  hideToolbar(selected, 1);
  hideMenubar(selected, 1);
  hideWindowUi(selected, 1);
  fitWindow(selected, 1);
  centerWindow(selected, 1);
  displayDocTitle(selected, 1);
  setMetadataFromFile(selected, "hello.pdf");
  removeMetadata(selected); 
  removeAttachedFiles(hello3);
  char data[] = {1,2,3,4,5,6,7,8,9,0};
  setMetadataFromByteArray(hello3, data, 10);
  twoUp(selected);
  int justone = range(1, 1); 
  padBefore(selected, justone);
  padAfter(selected, justone);
  stampOn(selected, hello3, justone);
  stampUnder(selected, hello3, justone);
  int combined = combinePages(selected, hello3);
  int pdfsa[] = {combined, selected};
  char* st1 = "one";
  char* st2 = "two";
  char* st3 = "";
  char* strings[2];
  strings[0] = st1;
  strings[1] = st2;
  int mergesamed = mergeSame(pdfsa, 2, 0, 0, strings);
  toFile(mergesamed, "mergesamed.pdf", 0, 0);
  struct position pos;
  pos.anchor = topLeft;
  pos.coord1 = 20.0;
  scaleContents(selected, justone, pos, 0.5);
  addText(selected, justone, "Some Text", pos, 1.0, 0, 0, 36.0, 0.0, 1.0, 0.0, 1);
  double minx;
  double maxx;
  double miny;
  double maxy;
  getMediaBox(selected, 1, &minx, &maxx, &miny, &maxy);
  printf("Media box: %f %f %f %f\n", minx, maxx, miny, maxy);
  getCropBox(selected, 1, &minx, &maxx, &miny, &maxy);
  printf("Crop box: %f %f %f %f\n", minx, maxx, miny, maxy);
  toFile(selected, "metadata.pdf", 0, 0); */
  return 0;
}
